version: '0.0.{build}'

branches:
  only:
    - master

configuration:
  - Debug
  - Release

environment:
  matrix:
    - compiler: msvc-16-seh
      generator: "Visual Studio 16 2019"
      build_system: cmake
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019

    - compiler: msvc-15-seh
      generator: "Visual Studio 15 2017"
      build_system: cmake
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015"
      build_system: cmake
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

for:
    - matrix:
        only:
            - configuration: Debug

      before_build:
          - ci\before_build_debug.sh
      build_script:
          - ci\build_script_debug.sh

for:
    - matrix:
        only:
            - configuration: Release

      before_build:
          - ci\before_build_release.sh
      build_script:
          - ci\build_script_release.sh

test_script:
    - ci\test_script.sh

after_test:
    - ps: .\ci\after_test.ps1
